GRAVITY = PVector(0, 0.0981)

DRAW_SIZE = PVector(700, 600)
WORLD_SIZE = PVector(600, 500)
WORLD_START = PVector(50, 20)

BALL_RADIUS = 10
BALL_DIAMETER = BALL_RADIUS * 2
LO_LIMIT = BALL_RADIUS
Y_HI_LIMIT = WORLD_SIZE.y - BALL_RADIUS
X_HI_LIMIT = WORLD_SIZE.x - BALL_RADIUS

COL_WORLD = 245
COL_BACKGROUND = 200

# WALL_BOUNCE = -1
# WALL_FRICTION = 1
WALL_BOUNCE = -0.9
WALL_FRICTION = 0.95

UP = PVector(0, -.2)
DOWN = PVector(0, .2)
LEFT = PVector(-.2, 0)
RIGHT = PVector(.2, 0)
