GRAVITY = PVector(0, 0.0981)

DRAW_SIZE = PVector(700, 600)
WORLD_SIZE = PVector(600, 500)
WORLD_START = PVector(50, 20)

BALL_RADIUS = 10
BALL_DIAMETER = BALL_RADIUS * 2
LO_LIMIT = BALL_RADIUS
Y_HI_LIMIT = WORLD_SIZE.y - BALL_RADIUS
X_HI_LIMIT = WORLD_SIZE.x - BALL_RADIUS

COL_WORLD = 245
COL_BACKGROUND = 200
